/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.magicregister;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Hacobby
 */
public class UI extends javax.swing.JFrame {

    private RegistroYControl inventario = new RegistroYControl();
    private DefaultTableModel modeloPrestacion;
    private DefaultTableModel modeloItem;
    private String msj;

    
    /**
     * Creates new form UI
     */
    public UI() {
        // Configuracion de las listas
        // Lista de prestamos 
        this.modeloItem = new DefaultTableModel(new Object[]{"Equipo", "Cantidad"}, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; // Hacer que todas las celdas no sean editables
            }
        };
        // Lista de items
        this.modeloPrestacion = new DefaultTableModel(new Object[]{"Cliente", "item", "Salon"}, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; // Hacer que todas las celdas no sean editables
            }
        };
        msj = "Trabajo en progreso, de momento solo puede registrar equipos\n y registrar prestamos de forma incompleta";
        
        initComponents();
        
        // Valores por defecto
        iniciarItemDefault();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        equiposPrestados = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        prestarEquipoButton = new javax.swing.JButton();
        recibirEquipoButton = new javax.swing.JButton();
        registrarEquipoButton = new javax.swing.JButton();
        registrarClienteButton = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        equiposDisponibles = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Proyecto Prestacion");
        setBackground(java.awt.Color.black);
        setForeground(java.awt.Color.black);
        setIconImages(null);
        setName("vistaPrincipal"); // NOI18N
        setResizable(false);

        equiposPrestados.setModel(this.modeloPrestacion);
        jScrollPane1.setViewportView(equiposPrestados);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setLabelFor(equiposPrestados);
        jLabel2.setText("Equipos disponibles");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setLabelFor(equiposPrestados);
        jLabel3.setText("Equipo Prestados");

        prestarEquipoButton.setText("Prestar equipo");
        prestarEquipoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prestarEquipoButtonActionPerformed(evt);
            }
        });

        recibirEquipoButton.setText("Recibir equipo");
        recibirEquipoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recibirEquipoButtonActionPerformed(evt);
            }
        });

        registrarEquipoButton.setText("Registrar equipo");
        registrarEquipoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarEquipoButtonActionPerformed(evt);
            }
        });

        registrarClienteButton.setText("Registrar cliente");
        registrarClienteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarClienteButtonActionPerformed(evt);
            }
        });

        equiposDisponibles.setModel(this.modeloItem);
        jScrollPane3.setViewportView(equiposDisponibles);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(recibirEquipoButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(registrarEquipoButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(registrarClienteButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(prestarEquipoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addComponent(prestarEquipoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(recibirEquipoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(registrarEquipoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(registrarClienteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void iniciarItemDefault() {
        this.inventario.agregarItem("Laptop", 10);
        this.inventario.agregarItem("Cable HDMI", 10);
        this.inventario.agregarItem("VideoBeam", 5);
        
        for (Item item : inventario.getInventario()) {
            this.modeloItem.addRow(new Object[]{item.getNombre(), item.getCantidad()});
        }
    }
    
    private void registrarEquipoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarEquipoButtonActionPerformed
        // TODO add your handling code here:
        String nombre = JOptionPane.showInputDialog("¿Que item va a registrar?");
        int cantidad = Integer.parseInt(JOptionPane.showInputDialog("¿Cuantos de " + nombre + " registrara?"));
        this.inventario.agregarItem(nombre, cantidad);
        
        this.modeloItem.setRowCount(0);
        
        for (Item item : inventario.getInventario()) {
            this.modeloItem.addRow(new Object[]{item.getNombre(), item.getCantidad()});
        }

    }//GEN-LAST:event_registrarEquipoButtonActionPerformed

    private void prestarEquipoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prestarEquipoButtonActionPerformed
        // TODO add your handling code here:
        String nombre = JOptionPane.showInputDialog("Ingrese el nombre del cliente");
        String ocupacion = JOptionPane.showInputDialog("Ingrese la ocupacion del cliente (Maestro/Alumno/Ejecutivo");
        int id = Integer.parseInt(JOptionPane.showInputDialog("ID del cliente (Universitario)"));
        String horaEntrega = JOptionPane.showInputDialog("Ingrese la hora del prestamo");
        String horaRecibo = JOptionPane.showInputDialog("Hora estimada de devolucion");
        String item = JOptionPane.showInputDialog("¿Que item se prestara?");
        int salon = Integer.parseInt(JOptionPane.showInputDialog("En que salon se usara el item"));
        
        this.inventario.agregarPrestamo(nombre, ocupacion, id, horaEntrega, horaRecibo, salon, item);
        
        this.modeloPrestacion.setRowCount(0);
        
        for (Prestacion prestacion : inventario.getEquiposPrestados()) {
            this.modeloPrestacion.addRow(new Object[]{prestacion.getNombre(), prestacion.getItem(), prestacion.getSalon()});
        }
    }//GEN-LAST:event_prestarEquipoButtonActionPerformed

    private void recibirEquipoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recibirEquipoButtonActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(rootPane, this.msj, "Caracteristica no disponible", 1);
    }//GEN-LAST:event_recibirEquipoButtonActionPerformed

    private void registrarClienteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarClienteButtonActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(rootPane, this.msj, "Caracteristica no disponible", 1);
    }//GEN-LAST:event_registrarClienteButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable equiposDisponibles;
    private javax.swing.JTable equiposPrestados;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton prestarEquipoButton;
    private javax.swing.JButton recibirEquipoButton;
    private javax.swing.JButton registrarClienteButton;
    private javax.swing.JButton registrarEquipoButton;
    // End of variables declaration//GEN-END:variables
}
